apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: webhook-site
  name: webhook-site
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: webhook-site
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f docker-compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: webhook-site
    spec:
      containers:
        - name: webhook-site
          args:
            - php
            - artisan
            - queue:work
            - --daemon
            - --tries=3
            - --timeout=10
          env:
            - name: APP_DEBUG
              value: "true"
            - name: APP_ENV
              value: dev
            - name: APP_LOG
              value: errorlog
            - name: APP_URL
              value: http://127.0.0.1:80
            - name: BROADCAST_DRIVER
              value: redis
            - name: CACHE_DRIVER
              value: redis
            - name: DB_CONNECTION
              value: sqlite
            - name: ECHO_HOST_MODE
              value: path
            - name: QUEUE_DRIVER
              value: redis
            - name: REDIS_HOST
              value: 127.0.0.1
          image: webhooksite/webhook.site
          ports:
            - containerPort: 80
              protocol: TCP
        - name: redis
          image: redis:alpine
          ports:
            - containerPort: 6379
              protocol: TCP
        - name: laravel-echo-server
          env:
            - name: ECHO_ALLOW_CORS
              value: "true"
            - name: ECHO_ALLOW_HEADERS
              value: '*'
            - name: ECHO_ALLOW_METHODS
              value: '*'
            - name: ECHO_ALLOW_ORIGIN
              value: '*'
            - name: ECHO_PROTOCOL
              value: http
            - name: ECHO_REDIS_HOSTNAME
              value: "127.0.0.1"
            - name: ECHO_REDIS_PORT
              value: "6379"
            - name: LARAVEL_ECHO_SERVER_AUTH_HOST
              value: http://127.0.0.1:80
            - name: LARAVEL_ECHO_SERVER_HOST
              value: 0.0.0.0
            - name: LARAVEL_ECHO_SERVER_PORT
              value: "6001"
          image: webhooksite/laravel-echo-server
          ports:
            - containerPort: 6001
              protocol: TCP
      restartPolicy: Always
